# Generated by Django 4.1.3 on 2022-11-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cellphone', models.PositiveBigIntegerField()),
                ('marketin_validation', models.BooleanField(default=False)),
                ('adress', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('document', models.PositiveBigIntegerField()),
            ],
        ),
    ]
