# Generated by Django 4.1.3 on 2022-11-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
